import { useState, useEffect } from 'react';
import Masonry from 'react-masonry-css';
import { mockArtworks, Artwork } from '@/lib/mock-data';
import { ImageCard } from '@/components/ImageCard';
import { Button } from '@/components/ui/button';
export function HomePage() {
  const [artworks, setArtworks] = useState<Artwork[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [page, setPage] = useState(1);
  const fetchArtworks = () => {
    setIsLoading(true);
    // Simulate network delay
    setTimeout(() => {
      // In a real app, you'd fetch from an API: `fetch(/api/artworks?page=${page})`
      // Here we just shuffle and append the mock data
      const newArtworks = [...mockArtworks].sort(() => 0.5 - Math.random());
      setArtworks(prev => [...prev, ...newArtworks]);
      setPage(prev => prev + 1);
      setIsLoading(false);
    }, 1000);
  };
  useEffect(() => {
    fetchArtworks();
  }, []); // Fetch initial data on mount
  const breakpointColumnsObj = {
    default: 5,
    1536: 4, // 2xl
    1280: 3, // xl
    1024: 3, // lg
    768: 2,  // md
    640: 1   // sm
  };
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="py-8 md:py-10 lg:py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-display font-bold text-foreground">
            Discover AI Masterpieces
          </h1>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            Explore a universe of art generated by artificial intelligence. Share your creations, build collections, and connect with a community of digital artists.
          </p>
        </div>
        <Masonry
          breakpointCols={breakpointColumnsObj}
          className="masonry-grid"
          columnClassName="masonry-grid_column"
        >
          {artworks.map((artwork, index) => (
            <ImageCard key={`${artwork.id}-${index}`} artwork={artwork} />
          ))}
        </Masonry>
        <div className="text-center mt-12">
          <Button onClick={fetchArtworks} disabled={isLoading} size="lg">
            {isLoading ? 'Loading...' : 'Load More'}
          </Button>
        </div>
      </div>
    </div>
  );
}