import { useState, useEffect } from 'react';
import Masonry from 'react-masonry-css';
import { useArtworksStore } from '@/store/artworks';
import { ImageCard } from '@/components/ImageCard';
import { Button } from '@/components/ui/button';
import { Artwork } from '@/lib/mock-data';
export function HomePage() {
  const allArtworks = useArtworksStore((state) => state.artworks);
  const [displayedArtworks, setDisplayedArtworks] = useState<Artwork[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [page, setPage] = useState(0);
  const itemsPerPage = 10;
  const loadMoreArtworks = () => {
    setIsLoading(true);
    setTimeout(() => {
      const nextPage = page + 1;
      const newArtworks = allArtworks.slice(0, nextPage * itemsPerPage);
      setDisplayedArtworks(newArtworks);
      setPage(nextPage);
      setIsLoading(false);
    }, 500);
  };
  useEffect(() => {
    // Initial load
    setPage(0);
    const initialArtworks = allArtworks.slice(0, itemsPerPage);
    setDisplayedArtworks(initialArtworks);
    setPage(1);
  }, [allArtworks]);
  const breakpointColumnsObj = {
    default: 5,
    1536: 4, // 2xl
    1280: 3, // xl
    1024: 3, // lg
    768: 2,  // md
    640: 1   // sm
  };
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="py-8 md:py-10 lg:py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-display font-bold text-foreground">
            Discover AI Masterpieces
          </h1>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            Explore a universe of art generated by artificial intelligence. Share your creations, build collections, and connect with a community of digital artists.
          </p>
        </div>
        <Masonry
          breakpointCols={breakpointColumnsObj}
          className="masonry-grid"
          columnClassName="masonry-grid_column"
        >
          {displayedArtworks.map((artwork) => (
            <ImageCard key={artwork.id} artwork={artwork} />
          ))}
        </Masonry>
        {displayedArtworks.length < allArtworks.length && (
          <div className="text-center mt-12">
            <Button onClick={loadMoreArtworks} disabled={isLoading} size="lg">
              {isLoading ? 'Loading...' : 'Load More'}
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}