import { useState, useEffect, useMemo } from 'react';
import Masonry from 'react-masonry-css';
import { useArtworksStore } from '@/store/artworks';
import { ImageCard } from '@/components/ImageCard';
import { Button } from '@/components/ui/button';
import { Artwork } from '@/lib/mock-data';
import { Badge } from '@/components/ui/badge';
import { SearchX } from 'lucide-react';
const popularTags = ['space', 'cyberpunk', 'fantasy', 'steampunk', 'abstract', 'dragon'];
export function HomePage() {
  const allArtworks = useArtworksStore((state) => state.artworks);
  const searchTerm = useArtworksStore((state) => state.searchTerm);
  const setSearchTerm = useArtworksStore((state) => state.setSearchTerm);
  const filterTag = useArtworksStore((state) => state.filterTag);
  const setFilterTag = useArtworksStore((state) => state.setFilterTag);
  const filteredArtworks = useMemo(() => {
    return allArtworks.filter(artwork => {
      const term = searchTerm.toLowerCase();
      const matchesSearch =
        artwork.title.toLowerCase().includes(term) ||
        artwork.artist.username.toLowerCase().includes(term) ||
        artwork.tags.some(tag => tag.toLowerCase().includes(term));
      const matchesTag = filterTag ? artwork.tags.includes(filterTag) : true;
      return matchesSearch && matchesTag;
    });
  }, [allArtworks, searchTerm, filterTag]);
  const [displayedArtworks, setDisplayedArtworks] = useState<Artwork[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [page, setPage] = useState(0);
  const itemsPerPage = 10;
  const loadMoreArtworks = () => {
    setIsLoading(true);
    setTimeout(() => {
      const nextPage = page + 1;
      const newArtworks = filteredArtworks.slice(0, nextPage * itemsPerPage);
      setDisplayedArtworks(newArtworks);
      setPage(nextPage);
      setIsLoading(false);
    }, 500);
  };
  useEffect(() => {
    setPage(0);
    const initialArtworks = filteredArtworks.slice(0, itemsPerPage);
    setDisplayedArtworks(initialArtworks);
    setPage(1);
  }, [filteredArtworks]);
  const breakpointColumnsObj = {
    default: 5,
    1536: 4,
    1280: 3,
    1024: 3,
    768: 2,
    640: 1
  };
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="py-8 md:py-10 lg:py-12">
        <div className="text-center mb-8">
          <h1 className="text-4xl md:text-5xl font-display font-bold text-foreground">
            Discover AI Masterpieces
          </h1>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            Explore a universe of art generated by artificial intelligence. Share your creations, build collections, and connect with a community of digital artists.
          </p>
        </div>
        <div className="flex justify-center items-center flex-wrap gap-2 mb-12">
          <Badge
            variant={filterTag === null ? 'default' : 'secondary'}
            onClick={() => setFilterTag(null)}
            className="cursor-pointer text-base px-4 py-2"
          >
            All
          </Badge>
          {popularTags.map(tag => (
            <Badge
              key={tag}
              variant={filterTag === tag ? 'default' : 'secondary'}
              onClick={() => setFilterTag(tag)}
              className="cursor-pointer text-base px-4 py-2 capitalize"
            >
              {tag}
            </Badge>
          ))}
        </div>
        {displayedArtworks.length > 0 ? (
          <Masonry
            breakpointCols={breakpointColumnsObj}
            className="masonry-grid"
            columnClassName="masonry-grid_column"
          >
            {displayedArtworks.map((artwork) => (
              <ImageCard key={artwork.id} artwork={artwork} />
            ))}
          </Masonry>
        ) : (
          <div className="text-center py-16 border-2 border-dashed rounded-lg">
            <SearchX className="mx-auto h-12 w-12 text-muted-foreground" />
            <h3 className="mt-4 text-lg font-semibold">No Results Found</h3>
            <p className="mt-1 text-sm text-muted-foreground">
              Try adjusting your search or filters to find what you're looking for.
            </p>
            {(searchTerm || filterTag) && (
              <Button
                variant="ghost"
                className="mt-4"
                onClick={() => {
                  setSearchTerm('');
                  setFilterTag(null);
                }}
              >
                Clear Search & Filters
              </Button>
            )}
          </div>
        )}
        {displayedArtworks.length < filteredArtworks.length && (
          <div className="text-center mt-12">
            <Button onClick={loadMoreArtworks} disabled={isLoading} size="lg">
              {isLoading ? 'Loading...' : 'Load More'}
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}